package com.prism.statistics.infrastructure.collect.inbox;

public enum CollectInboxType {

    PULL_REQUEST_OPENED,
    PULL_REQUEST_CLOSED,
    PULL_REQUEST_SYNCHRONIZED,
    PULL_REQUEST_READY_FOR_REVIEW,
    PULL_REQUEST_REOPENED,
    PULL_REQUEST_CONVERTED_TO_DRAFT,
    PULL_REQUEST_LABEL_ADDED,
    PULL_REQUEST_LABEL_REMOVED,
    REVIEW_SUBMITTED,
    REVIEWER_ADDED,
    REVIEWER_REMOVED,
    REVIEW_COMMENT_CREATED,
    REVIEW_COMMENT_EDITED,
    REVIEW_COMMENT_DELETED
}
