DROP TABLE IF EXISTS pr_file_histories;
DROP TABLE IF EXISTS pr_change_histories;
DROP TABLE IF EXISTS pr_state_change_histories;
DROP TABLE IF EXISTS pr_label_histories;
DROP TABLE IF EXISTS pr_labels;
DROP TABLE IF EXISTS requested_reviewer_change_histories;
DROP TABLE IF EXISTS requested_reviewers;
DROP TABLE IF EXISTS commits;
DROP TABLE IF EXISTS pr_files;
DROP TABLE IF EXISTS pull_requests;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS test_audit_entity;
DROP TABLE IF EXISTS projects;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    nickname_value VARCHAR(255),
    state VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    registration_id VARCHAR(255),
    social_id VARCHAR(255),
    CONSTRAINT uq_user_identities_social UNIQUE (registration_id, social_id)
);

CREATE TABLE IF NOT EXISTS test_audit_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name VARCHAR(255),
    repository_url VARCHAR(255),
    api_key VARCHAR(255),
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    project_id BIGINT NOT NULL,
    author_github_id VARCHAR(255),
    pr_number INT,
    title VARCHAR(255),
    state VARCHAR(50),
    link VARCHAR(500),
    changed_file_count INT,
    addition_count INT,
    deletion_count INT,
    commit_count INT,
    pr_created_at TIMESTAMP,
    merged_at TIMESTAMP,
    closed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pr_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    file_name VARCHAR(500),
    change_type VARCHAR(50),
    additions INT,
    deletions INT
);

CREATE TABLE IF NOT EXISTS commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    commit_sha VARCHAR(255),
    committed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pr_state_change_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    previous_state VARCHAR(50),
    new_state VARCHAR(50),
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pr_change_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    changed_file_count INT,
    addition_count INT,
    deletion_count INT,
    commit_count INT,
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pr_file_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    file_name VARCHAR(500),
    previous_file_name VARCHAR(500),
    change_type VARCHAR(50),
    additions INT,
    deletions INT,
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pr_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    label_name VARCHAR(255),
    labeled_at TIMESTAMP,
    CONSTRAINT uq_pr_labels UNIQUE (pull_request_id, label_name)
);

CREATE TABLE IF NOT EXISTS pr_label_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    label_name VARCHAR(255),
    action VARCHAR(50),
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requested_reviewers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    github_mention VARCHAR(255),
    github_uid BIGINT,
    requested_at TIMESTAMP,
    CONSTRAINT uq_requested_reviewers UNIQUE (pull_request_id, github_uid)
);

CREATE TABLE IF NOT EXISTS requested_reviewer_change_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    github_mention VARCHAR(255),
    github_uid BIGINT,
    action VARCHAR(50),
    changed_at TIMESTAMP
);
