DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    nickname_value VARCHAR(255),
    state VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    registration_id VARCHAR(255),
    social_id VARCHAR(255),
    CONSTRAINT uq_user_identities_social UNIQUE (registration_id, social_id)
);

CREATE TABLE IF NOT EXISTS test_audit_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255)
)
