DROP TABLE IF EXISTS pull_request_file_histories;
DROP TABLE IF EXISTS pull_request_content_histories;
DROP TABLE IF EXISTS pull_request_state_histories;
DROP TABLE IF EXISTS pull_request_label_histories;
DROP TABLE IF EXISTS pull_request_labels;
DROP TABLE IF EXISTS requested_reviewer_histories;
DROP TABLE IF EXISTS requested_reviewers;
DROP TABLE IF EXISTS review_comments;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS commits;
DROP TABLE IF EXISTS pull_request_files;
DROP TABLE IF EXISTS pull_requests;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS test_audit_entity;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS pull_request_opened_commit_densities;
DROP TABLE IF EXISTS pull_request_opened_change_summaries;
DROP TABLE IF EXISTS pull_request_opened_file_change_diversities;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    nickname_value VARCHAR(255),
    state VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    registration_id VARCHAR(255),
    social_id VARCHAR(255),
    CONSTRAINT uq_user_identities_social UNIQUE (registration_id, social_id)
);

CREATE TABLE IF NOT EXISTS test_audit_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name VARCHAR(255),
    repository_url VARCHAR(255),
    api_key VARCHAR(255),
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    github_pull_request_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    user_name VARCHAR(255),
    user_id BIGINT,
    pull_request_number INT,
    head_commit_sha VARCHAR(255),
    title VARCHAR(255),
    state VARCHAR(50),
    link VARCHAR(500),
    changed_file_count INT,
    addition_count INT,
    deletion_count INT,
    commit_count INT,
    github_created_at TIMESTAMP,
    github_merged_at TIMESTAMP,
    github_closed_at TIMESTAMP,
    CONSTRAINT uq_pull_requests_github_pull_request_id UNIQUE (github_pull_request_id)
);

CREATE TABLE IF NOT EXISTS pull_request_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    file_name VARCHAR(500),
    change_type VARCHAR(50),
    additions INT,
    deletions INT
);

CREATE TABLE IF NOT EXISTS commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    commit_sha VARCHAR(255),
    committed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pull_request_state_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    head_commit_sha VARCHAR(255),
    previous_state VARCHAR(50),
    new_state VARCHAR(50),
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pull_request_content_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    head_commit_sha VARCHAR(255),
    changed_file_count INT,
    addition_count INT,
    deletion_count INT,
    commit_count INT,
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pull_request_file_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    head_commit_sha VARCHAR(255),
    file_name VARCHAR(500),
    previous_file_name VARCHAR(500),
    change_type VARCHAR(50),
    additions INT,
    deletions INT,
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pull_request_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    github_pull_request_id BIGINT NOT NULL,
    pull_request_id BIGINT,
    head_commit_sha VARCHAR(255),
    label_name VARCHAR(255),
    labeled_at TIMESTAMP,
    CONSTRAINT uq_pull_request_labels UNIQUE (github_pull_request_id, label_name)
);

CREATE TABLE IF NOT EXISTS pull_request_label_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    github_pull_request_id BIGINT NOT NULL,
    pull_request_id BIGINT,
    head_commit_sha VARCHAR(255),
    label_name VARCHAR(255),
    action VARCHAR(50),
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requested_reviewers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT,
    github_pull_request_id BIGINT NOT NULL,
    head_commit_sha VARCHAR(255),
    user_name VARCHAR(255),
    user_id BIGINT,
    requested_at TIMESTAMP,
    CONSTRAINT uq_requested_reviewers UNIQUE (github_pull_request_id, user_id)
);

CREATE TABLE IF NOT EXISTS requested_reviewer_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT,
    github_pull_request_id BIGINT NOT NULL,
    head_commit_sha VARCHAR(255),
    user_name VARCHAR(255),
    user_id BIGINT,
    action VARCHAR(50),
    changed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT,
    github_pull_request_id BIGINT NOT NULL,
    github_review_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    review_state VARCHAR(50) NOT NULL,
    head_commit_sha VARCHAR(255) NOT NULL,
    body TEXT,
    comment_count INT NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_reviews_github_review_id UNIQUE (github_review_id)
);

CREATE TABLE IF NOT EXISTS review_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    review_id BIGINT,
    github_comment_id BIGINT NOT NULL,
    github_review_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    path VARCHAR(500) NOT NULL,
    start_line INT,
    end_line INT NOT NULL,
    side VARCHAR(50) NOT NULL,
    commit_sha VARCHAR(255) NOT NULL,
    parent_comment_id BIGINT,
    user_name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    github_created_at TIMESTAMP NOT NULL,
    github_updated_at TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_review_comments_github_comment_id UNIQUE (github_comment_id)
);

CREATE TABLE IF NOT EXISTS pull_request_opened_commit_densities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    commit_density_per_file DECIMAL(19, 4) NOT NULL,
    commit_density_per_change DECIMAL(19, 6) NOT NULL
);

CREATE TABLE IF NOT EXISTS pull_request_opened_file_change_diversities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    change_type VARCHAR(50) NOT NULL,
    count INT NOT NULL,
    ratio DECIMAL(19, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS pull_request_opened_change_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    pull_request_id BIGINT NOT NULL,
    total_changes INT NOT NULL,
    avg_changes_per_file DECIMAL(19, 4) NOT NULL
);
